name: test

on:
  schedule:
    - cron: '50 18 * * *'
  workflow_dispatch:

permissions:
    contents: read
    actions: write

env:
  HTTP_PROXY: http://tvkk13579:abbabf76a5@216.227.222.97:12323
  HTTPS_PROXY: http://tvkk13579:abbabf76a5@216.227.222.97:12323
  NO_PROXY: localhost,127.0.0.1

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
   
    - name: Configure Docker Proxy and DNS
      run: |
        sudo mkdir -p /etc/systemd/system/docker.service.d
        echo '[Service]' | sudo tee /etc/systemd/system/docker.service.d/http-proxy.conf
        echo 'Environment="HTTP_PROXY=http://your-proxy-server:port"' | sudo tee -a /etc/systemd/system/docker.service.d/http-proxy.conf
        echo 'Environment="HTTPS_PROXY=https://your-proxy-server:port"' | sudo tee -a /etc/systemd/system/docker.service.d/http-proxy.conf
        echo 'Environment="NO_PROXY=localhost,127.0.0.1"' | sudo tee -a /etc/systemd/system/docker.service.d/http-proxy.conf
        sudo systemctl daemon-reload
        sudo systemctl restart docker
        echo '{
          "dns": ["8.8.8.8", "8.8.4.4"],
          "proxies": {
            "default": {
              "httpProxy": "http://tvkk13579:abbabf76a5@216.227.222.97:12323",
              "httpsProxy": "http://tvkk13579:abbabf76a5@216.227.222.97:12323",
              "noProxy": "localhost,127.0.0.1"
            }
          }
        }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: app
      run: |
        chmod +x entrypoint.sh

    - name: app run
      run: |
        bash entrypoint.sh
